name: Wallpaper Automation and Deployment

    # 每天UTC时间20:00运行（北京时间次日6:00）
    on:
      schedule:
        - cron: '0 20 * * *'
      # 允许手动触发工作流
      workflow_dispatch:

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        
        steps:
          # 步骤1: 检出代码仓库
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              # 确保获取所有历史记录，以便正确推送
              fetch-depth: 0

          # 步骤2: 设置Python环境
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.9'  # 根据你的需求选择合适的Python版本

          # 步骤3: 安装依赖（如果需要）
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          # 步骤4: 运行main.py获取并保存壁纸
          - name: Run wallpaper script
            run: python main.py

          # 步骤5: 配置Git用户信息
          - name: Configure Git
            run: |
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"

          # 步骤6: 切换到page分支并合并更改
          - name: Deploy to page branch
            run: |
              # 创建一个临时目录保存当前更改
              mkdir -p temp_deploy
              cp -r * temp_deploy/ || true
              
              # 切换到page分支，如果不存在则创建
              if git rev-parse --verify page; then
                git checkout page
              else
                git checkout -b page
              fi
              
              # 将临时目录的内容复制到当前分支（覆盖现有文件）
              cp -r temp_deploy/* . || true
              
              # 添加并提交更改
              git add .
              git commit -m "Automated wallpaper update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
              
              # 推送更改到page分支
              git push origin page
    
